%
% runall for ENG1060 Assignment S2 2016
%
% DO NOT EDIT THIS FILE except to add your name and ID and date
%
% Your name: Takudzwa Frank Mukarakate
% Your student ID: 27754251
% Date you wrote it: 14-Oct-2016

% First do Q1

close all
clear all
clc

Q1a; pause;

Q1b; pause;

Q1c; pause;

Q1d; pause;

Q1e; pause;

Q1f; pause;

% Then do Q2

close all
clear all
clc

Q2a; pause;

Q2b; pause;

Q2c; pause;

close all
clear all
clc
